// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Ahorcado;

import java.util.Scanner;

import Ahorcado.Horca;
import Ahorcado.Palabra;
import sun.applet.Main;

/************************************************************/
/**
 * 
 */
public class Partida {
	/**
	 * 
	 */
	public Horca horca;
	/**
	 * 
	 */
	public Palabra palabra;

	/**
	 * 
	 */
	public void mostrarProgreso() {
		horca.dibujar();
		palabra.mostrarResultados();
	}

	/**
	 * 
	 * @return letra 
	 */
	public char pedirLetra() {
		Scanner entrada= new Scanner(System.in);
		System.out.println("Introdusca una letra : ");
		char letra= entrada.nextLine().charAt(0);
		return letra;
	}

	/**
	 * @return 
	 * 
	 */
	public boolean resolver() {
		Scanner entrada= new Scanner(System.in);
		System.out.println("Introduce respuesta ");
		return palabra.comprobarPalabra(entrada.nextLine());
	}
	

	/**
	 * Compreuba tanto si hemos agotado los fallos como si hemos acertado
	 * todas las teclas.
	 * @return true si Hemos ganado o perdido, false  si todavia jugamos
	 */
	public boolean comprobarFinal() {
		return horca.comprobarSiPerdido() || palabra.comprobarSiGanado();
	}
	public static void main(String[] args) {
		
	}
};
